## Heatwave Predictor

NOAA DCHN-D S3 bucket: https://noaa-ghcn-pds.s3.amazonaws.com/index.html

In [1]:
import pandas as pd

In [3]:
# link to 
df = pd.read_parquet("https://noaa-ghcn-pds.s3.amazonaws.com/parquet/by_year/YEAR%3D2024/ELEMENT%3DTMAX/c3200a58eef54100b1bf9ef4d5b4415b_0.snappy.parquet")
df

                 ID      DATE  DATA_VALUE M_FLAG Q_FLAG S_FLAG OBS_TIME
0       ASN00026105  20240101         235   None   None      a     None
1       ASN00026091  20240101         270   None   None      a     None
2       ASN00026095  20240101         226   None   None      a     None
3       ASN00026099  20240101         289   None   None      a     None
4       ASN00026100  20240101         290   None   None      a     None
...             ...       ...         ...    ...    ...    ...      ...
499995  USC00344298  20240212         111   None   None      7     2300
499996  USC00344451  20240212         100   None   None      7     0800
499997  USC00341726  20240212         133   None   None      7     2400
499998  USC00341743  20240212         117   None   None      7     2400
499999  USC00341756  20240212          89   None   None      7     2400

[500000 rows x 7 columns]